name: 'flutter_podcast_app'
version: '1.0.0+1'
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
description: A new Flutter project.
dependencies:
  animations: '^2.0.1'
  cloud_firestore: '^5.0.1'
  cupertino_icons: '^1.0.2'
  curved_navigation_bar: '^1.0.6'
  dio: '^5.7.0'
  file: '^6.1.4'
  firebase_auth: '^5.3.3'
  firebase_core: '^3.8.0'
  firebase_storage: '^12.3.6'
  flutter:
    sdk: flutter
  flutter_feather_icons: '^2.0.0+1'
  get: '^4.6.6'
  google_fonts: '^6.2.1'
  http: '^1.2.2'
  just_audio: '^0.9.14'
  responsive_sizer: '^3.3.1'
dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: '^1.0.5'
  very_good_analysis: '^6.0.0'
flutter:
  uses-material-design: true
  assets:
    - 'assets/images/intro_images/'
    - assets/images/
    - assets/audio/
